Tasmota Arduino compatible to Tasmota IDF 5.2.2
* Tasmota changes

* revert WiFiClient - rename flush() to clear() https://github.com/espressif/arduino-esp32/pull/9453/files since it uneeded brakes many libs and code
* optional Ethernet support (JL1101 driver added)
* esp-modem only esp32, esp32s2 and esp32s3
* remove `OpenThread`
* remove all BT BLE libraries
* remove SPIFFS
* remove Client Secure
* remove Provisioning
* remove TfLite, Insights and Rainmaker

* Arduino changes to make compatible IDF 5.2.x

fixMe: PPP.cpp:

```
/Users/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/libraries/PPP/src/PPP.cpp: In member function 'bool PPPClass::begin(ppp_modem_model_t, uint8_t, int)':
/Users/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/libraries/PPP/src/PPP.cpp:273:37: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'uart_port_t' [-fpermissive]
  273 |   dte_config.uart_config.port_num = _uart_num;
      |                                     ^~~~~~~~~
      |                                     |
      |                                     uint8_t {aka unsigned char}
```