temp disable since compile error with IDF 5.2
```
/Users/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/libraries/PPP/src/PPP.cpp: In member function 'bool PPPClass::begin(ppp_modem_model_t, uint8_t, int)':
/Users/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/components/arduino/libraries/PPP/src/PPP.cpp:273:37: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'uart_port_t' [-fpermissive]
  273 |   dte_config.uart_config.port_num = _uart_num;
      |                                     ^~~~~~~~~
      |                                     |
      |                                     uint8_t {aka unsigned char}
```